language: node_js
node_js:
- '4.2'
before_deploy:
- 'npm run build'
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: c96cenmKSFueZ6tl4vAo2uzLJYhRMghmrANmDx4QuPUYLN4rIRCTrngHGg0KxJLaVCSCOHOK1iWYKyEX16RKU/cA/9srDisyO195P7euORhlwRnFkznxCeiSXgkpr9TBjNLgWTQspdbZj4/mIGUtINpapxIZBmR9hc1Nti+2znT8FZz2j7CAn3ohaJ5VrOqh6o9neVBgP8bmdFDNbqK8L7R1OuX57vYEsQAy50MuaZTfVpKRCFMcwD2gGp+U1bAwA4leX73OvOwIRdLhvCrmbZTVvQUjYS8p/fiRTx74CeM1stXTYXyOmb0PGkxWZqT0L0sgcDPU0KAuGwzJVZq4Hzt3s7V8AfYuEMZr3jm9W/Phtk60jddmJ+G1diGs7hzWNp8lZR+D5thTcyA6BuOsUb4ytGhY38qhJQYgFDBp61UC+udC9fHa31ioNzk9NIUBzNKzjex+8aBI/AnCNzK8bx3KQxiK/9yFYpihkTOFs0LVUruTa1F3tqyWBCoW5frBEkBalpvy+DfIUResvLB9qaNT1CuCn5z2F29YsYUMVkfGc6Jhx/YFQ+7auQweiD4G/9y1dpWJTF7+rEHnsIm4C9rFj+3k/qFX1K3RMuZz7XSnNU5EydJnJqASMGOPZmxPkhnFruWzgOOC4Y7nQX7HdDEp0F8JVm+d1OOqsMqyq7s=
  file: dist/singpath.zip
  on:
    repo: singpath/singpath
    tags: true
