language: node_js
node_js:
- '4.2'
before_deploy:
- 'npm install -g jspm'
- 'jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN'
- 'jspm install -y'
- 'npm run build'
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: c96cenmKSFueZ6tl4vAo2uzLJYhRMghmrANmDx4QuPUYLN4rIRCTrngHGg0KxJLaVCSCOHOK1iWYKyEX16RKU/cA/9srDisyO195P7euORhlwRnFkznxCeiSXgkpr9TBjNLgWTQspdbZj4/mIGUtINpapxIZBmR9hc1Nti+2znT8FZz2j7CAn3ohaJ5VrOqh6o9neVBgP8bmdFDNbqK8L7R1OuX57vYEsQAy50MuaZTfVpKRCFMcwD2gGp+U1bAwA4leX73OvOwIRdLhvCrmbZTVvQUjYS8p/fiRTx74CeM1stXTYXyOmb0PGkxWZqT0L0sgcDPU0KAuGwzJVZq4Hzt3s7V8AfYuEMZr3jm9W/Phtk60jddmJ+G1diGs7hzWNp8lZR+D5thTcyA6BuOsUb4ytGhY38qhJQYgFDBp61UC+udC9fHa31ioNzk9NIUBzNKzjex+8aBI/AnCNzK8bx3KQxiK/9yFYpihkTOFs0LVUruTa1F3tqyWBCoW5frBEkBalpvy+DfIUResvLB9qaNT1CuCn5z2F29YsYUMVkfGc6Jhx/YFQ+7auQweiD4G/9y1dpWJTF7+rEHnsIm4C9rFj+3k/qFX1K3RMuZz7XSnNU5EydJnJqASMGOPZmxPkhnFruWzgOOC4Y7nQX7HdDEp0F8JVm+d1OOqsMqyq7s=
  file: dist/singpath.zip
  on:
    repo: singpath/singpath
    tags: true
env:
  global:
    secure: BrnsHjl+3r3nxPNceQpG6ltCt5CVzDkV9u4AaN8lndau047ckiGs/cdyY0tQQ/soLf5jOArT3WaVgeMuME+G+KA91i+87vmEBIHaKP0ifmkynyoD5BCxOQDHqF0RkGJSuvNhCn57m8Xt35AErxj8UpOedRqJ0eDZKAj02eUtAXUxc6kNN0TfGfHWr0iEvl3AC9FbCgJhjmJ3J1nI/BhvEwW3f6tgvyrlQvMwEyS3wqcr8Kx9fhMKF5FbOm8qajD8+OloMd47jgwWYIzG2EGvxjDJa250Dqn57Ek+YdPnDaQhA/XDkAr3zO7CcslOgjE8hf2RHEgMHy2+KnQ01cey4hBxunb+Zo11T+BH13bG0J599n81uAsxuYffAX8TUe3c15yoRIEXZi8wwlzpJI1tiNA+Gvv57X0prj1P9agt039bl07D1GgE1qiu6JPw0mQQ8W0NszIiLBJR0ZKNy1KGdCEXCUZ8fJMdYtnSFubNAPMI2j3/dHlhaVeWolHJ88fZ0FJrOu3R6q5eFI4ZvKX5jXGrxZw0yOf0e/tGsqCQe0vC+4HyaoElFnXIPTF5EfMB3mnLkbBXw1PHRmOZqpmHYvKeyLawZShGnw45mrq0yQUC4uWot2iRFm59pwFzWKOO3MhQsJHE1wm4F8cDKSgv558+tMl43d4YhSeP/tWc1Pw=
